#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavigationDrawer.Resource", IsApplication=true)]

namespace NavigationDrawer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int planets_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int horizontal_page_margin = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int margin_huge = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int margin_large = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int margin_medium = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int margin_small = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int margin_tiny = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int vertical_page_margin = 2131165190;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int earth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_drawer = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int jupiter = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mars = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mercury = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int neptune = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_dashboard_item_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int saturn = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tile = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int uranus = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int venus = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int action_websearch = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int content_frame = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int drawer_layout = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int image = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int left_drawer = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_navigation_drawer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int drawer_list_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_planet = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int sample_dashboard_item = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int navigation_drawer = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int action_websearch = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int app_not_available = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int drawer_close = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int drawer_open = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int intro_message = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int navigationdraweractivity_description = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int navigationdraweractivity_title = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Base = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Sample = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Widget = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Widget_SampleContentContainer = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Widget_SampleDashboard_Grid = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int Widget_SampleDashboard_Item = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int Widget_SampleDashboard_Item_Description = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int Widget_SampleDashboard_Item_Title = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int Widget_SampleMessage = 2131099653;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
